### PR TITLE
Add error message dialogs, Add CCW winding flag

### PR DESCRIPTION
**Pull request by underscorediscovery**
Error messages rather than silent logging:
screen 2015-09-01 at 2 54 39 am

CCW Flag for exporting to non CW engines:
screen 2015-09-01 at 2 54 51 am

Also:
- I bumped the versions - tested only on Blender-2.75
- The diff between the scripts is a commit comment below, since the file is new it's less clear.

### CODE REVIEW

**Comment by underscorediscovery** [comment]
Also realized I should have checked existing PR's! There seems to be some overlap on the error messages.

**Comment by shakesoda** [comment]
I'm not entirely sure an option to reverse winding is a good idea. I had originally implemented that too, but then I ran into the issue of my IQM models not having consistent winding and there being no way to tell - not good. Instead I reverted that change and just change the winding in the loader, since that's just a matter of swapping triangle indices 2/3.

+1 for better error reporting, though.

**Comment by underscorediscovery** [comment]
Hmm curious @shakesoda thanks for the thoughts. 
I reversed the full order not just 2/3, which may matter to why the indices being weird.

I agree about the winding being unknown from file to file, but adding an extra byte was a bit overreaching for discussion. It's probably good to see what the goals/vision are - I would be ok with it being forced but changing windings on load time adds huge expense, but it also demeans the goals of the library directly by slowing it down and adding importer complexity, increasing the chances of error etc.

I think the option is innocuous enough as a starting point for discussion, though!

**Comment by leilei-** [comment]
It's good that I see a message like "No armature selected" up and front.  Immediate feedback is not siomething you should shut up, not everyone it's going to know and pay attention to a console window (which isn't even shown up after Blender boots)

**Pull request closed without merging**
